Add Russian translations
modrinth/translations pull request #10
Opened 2022-05-28 20:02 UTC by Brawaru

2022-05-28 20:08 UTC, Brawaru reviewed
Вот так вот

2022-05-28 20:08 UTC, Brawaru commented on ru.json
> +		"misc": "Разное"
В целом не уверен в каком склонении писать теги, учитывая что они и для мод паков и для модов.

2022-05-28 20:08 UTC, Brawaru commented on ru.json
> +		"decoration": "Декорации",
Декоративные?

2022-05-28 20:08 UTC, Brawaru commented on ru.json
> +		"cursed": "",
?!

2022-05-28 20:08 UTC, Brawaru commented on ru.json
> +		"lightweight": "Лёгкий",
Легковесный?

2022-05-28 20:08 UTC, Brawaru commented on ru.json
> +		"combat": "Сражения",
?

2022-05-28 20:08 UTC, Brawaru commented on ru.json
> +			"heading": "Legal",
Правовой материал?

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +		"description": "Modrinth — программное обеспечение с открытым кодом.",
```suggestion
		"description": "Modrinth — сервис с открытым кодом.",
```
Подглядел в Мастодоне

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"system": "Системная тема",
```suggestion
				"system": "Тема системы",
```
или браузера (например, в Firefox можно менять)

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"oled": "OLED тема"
```suggestion
				"oled": "OLED-тема"
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"ru-RU": "Русский (Россия)"
```suggestion
				"ru": "Русский"
```
Надо бы ещё и файл в `ru.json` переименовать

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +			"404": "Ух ох, похоже вы заблудились в [лабиринте](https://github.com/modrinth/labrinth).<br/>Страница, которую вы ищете, не найдена.",
```suggestion
			"404": "Ой-йо, похоже вы заблудились в лабиринте.<br/>Страница, которую вы ищете, не найдена.",
```
Надо бы поставить другие междометия, например `Ой-йо`, `Ого` или `Ох`.

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +			"default": "Произошла непридвиденная ошибка"
```suggestion
			"default": "Произошла непредвиденная ошибка"
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +		"settings": "Настойки",
```suggestion
		"settings": "Настройки",
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +			"donate": "Пожертовать",
```suggestion
			"donate": "Пожертвовать",
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +			"github_profile": "Профиль GitHub",
```suggestion
			"github_profile": "Профиль на GitHub",
```
`в` или `на`?

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"plural": "Мод(ов)",
```suggestion
				"plural": "Моды",
```
тут уже plural

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"singular": "Набор модов",
```suggestion
				"singular": "Сборка модов",
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"plural": "Наборы модов",
```suggestion
				"plural": "Сборки модов",
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +				"search": "Поиск наборов модов..."
```suggestion
				"search": "Поиск сборок модов..."
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +		"unknown": "Неивестно"
```suggestion
		"unknown": "Неизвестно"
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +		"cursed": "",
```suggestion
		"cursed": "Проклятые",
```

2022-05-28 20:23 UTC, WerySkok commented on ru.json
> +		"combat": "Сражения",
мб "Боевые"?

2022-05-28 20:25 UTC, Brawaru commented on ru.json
> +				"plural": "Наборы модов",
Ой, точно, у нас же их просто «Сборками» называют, может вообще модов убрать?

2022-05-28 20:27 UTC, WerySkok commented on ru.json
> +				"plural": "Наборы модов",
Как бы не путать тогда со сборками плагинов для серверов...

2022-05-28 20:27 UTC, Brawaru commented on ru.json
> +			"404": "Ух ох, похоже вы заблудились в [лабиринте](https://github.com/modrinth/labrinth).<br/>Страница, которую вы ищете, не найдена.",
Ой-ёй может быть? Я не слышал чтобы кто-то говорил «ой-йо» в таком ключе, только «ой-йо, ты погляди что он творит».

2022-05-28 20:53 UTC, WerySkok commented on ru.json
> +			"404": "Ух ох, похоже вы заблудились в [лабиринте](https://github.com/modrinth/labrinth).<br/>Страница, которую вы ищете, не найдена.",
Я не нашёл литературных примеров использования `Ой-ёй`

2022-05-28 20:56 UTC, WerySkok commented on ru.json
> +		"lightweight": "Лёгковесный",
```suggestion
		"lightweight": "Легковесные",
```

2022-05-28 20:57 UTC, Brawaru commented on ru.json
> +			"404": "Ух ох, похоже вы заблудились в [лабиринте](https://github.com/modrinth/labrinth).<br/>Страница, которую вы ищете, не найдена.",
Reverso Context знает об этом варианте: https://context.reverso.net/translation/russian-english/%D0%9E%D0%B9-%D1%91%D0%B9.

2022-05-28 21:46 UTC, WerySkok commented on ru.json
> +			"404": "Ух ох, похоже вы заблудились в [лабиринте](https://github.com/modrinth/labrinth).<br/>Страница, которую вы ищете, не найдена.",
ну тогда хорошо

2022-05-29 00:27 UTC, Felix14-v2 commented on ru.json
> +		"decoration": "Декорации",
Просто "декор", вариант универсальнее.

2022-05-29 01:36 UTC, Felix14-v2 requested changes
Множественные улучшения.

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +		"decoration": "Декоративные",
```suggestion
		"decoration": "Декор",
```
Как я и писал в Дискорде,  к этой категории относятся и косметические моды для клиента, поэтому `декорации` неуместно. Возможно, стоит рассмотреть вариант `косметика` (в Mod Manager так и переведено, кстати).

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +		"storage": "Хранилища",
```suggestion
		"storage": "Инвентарь",
```
Ещё во время перевода Mod Manager понял, что многие моды в этой категории к хранилищам отношения не имеют, но специализируются на твиках инвентаря и управлении им(и). "Инвентарь" — общий термин, который бы решил проблему отхождения тематики таких модов от названия категории.

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +		"combat": "Боевые",
```suggestion
		"combat": "Боёвка",
```
Лучшая согласованность со звучанием названий других категорий.

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +		"lightweight": "Легковесный",
```suggestion
		"lightweight": "Легковесные",
```
Согласованность с названиями других категорий.

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +		"multiplayer": "Мультиплеер",
```suggestion
		"multiplayer": "Сетевая игра",
```
Скорее всего, придётся согласовать с нынешним официальным переводом этого термина.

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +		"good": "Норм",
Не нашёл в UI этой и последующей строки, но неформальность режет глаз. В каком контексте находятся эти строки?

2022-05-29 01:36 UTC, Felix14-v2 commented on ru.json
> +				"optional": "Необязательно",
```suggestion
				"optional": "Опционально",
```
Используется в обозначении рабочей среды мода/модпака, этот вариант уместнее.

2022-05-29 01:46 UTC, Brawaru commented on ru.json
> +				"system": "Тема системы",
До этого @WerySkok предложил «тема системы» >_>

2022-05-29 01:58 UTC, Brawaru commented on ru.json
> +		"good": "Норм",
Это тестовые категории на https://staging.modrinth.com/modpacks.

2022-05-29 04:17 UTC, Felix14-v2 commented on ru.json
> +				"system": "Тема системы",
И я удивлён, что это предложение приняли. У нас же 2 другие фразы написаны в аналогичной форме, зачем форму написания третьей менять?

2022-05-29 04:27 UTC, Felix14-v2 commented
А давайте переведём `kitchen-sink` как `солянка`? Кажется, это идеальный как по смыслу, так и по длине вариант.

2022-05-29 04:47 UTC, Brawaru commented on ru.json
> +				"system": "Тема системы",
Я подумал так: системная может предполагать вид системы (как System LAF), тема системы больше «тема, выбранная в системе».

2022-05-29 05:07 UTC, Brawaru commented
@Felix14-v2 

![Скриншот сообщений Discord. Сообщения от robotkoer: «How did others translate "kitchen sink"? I did "something for everybody"», «oh actually French translator suggested the equivalent of "hodgepodge", gonna use that as well». Сообщение от Brawaru: «yeah, was thinking of similar translation, russian would be ‘сборная солянка’, but sounds rather informal 🤔»](https://user-images.githubusercontent.com/10401817/170852700-cc4be2f6-490b-46a6-b1f4-9bb32373bc85.png)

2022-05-29 05:21 UTC, Felix14-v2 commented
Ну, в отсутствии альтернатив, и такой вариант сойдёт, я думаю. Был ещё один лаконичный перевод, `всё в одном`, он более формальный. Но и чуть сильнее удалён от оригинального смысла.

2022-05-29 05:42 UTC, Brawaru commented
Да мне тоже «сборная солянка» нравится, думаю выражение весьма распространённое на русском.

2022-05-29 05:45 UTC, Felix14-v2 commented
> Да мне тоже «сборная солянка» нравится, думаю выражение весьма распространённое на русском.

Вот только вместе с прилагательным `сборная` это обозначает исключительно блюдо, а просто `солянка` в переносном значении — всё, что состоит из большого количества несвязанных компонентов.

2022-05-29 05:56 UTC, Brawaru commented
Никогда не слышал чтобы использовали «солянка» само по себе в таком контексте, как раз наоборот «солянка» — блюдо, а «сборная солянка» в обиходе как «смесь всего и вся».

Викисловарь тоже о том же:
- [сборная солянка](https://ru.wiktionary.org/wiki/%D1%81%D0%B1%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%81%D0%BE%D0%BB%D1%8F%D0%BD%D0%BA%D0%B0)
- [солянка](https://ru.wiktionary.org/wiki/%D1%81%D0%BE%D0%BB%D1%8F%D0%BD%D0%BA%D0%B0)

2022-05-29 06:00 UTC, Felix14-v2 commented
> наоборот «солянка» — блюдо, а «сборная солянка» в обиходе как «смесь всего и вся».
> 
> Викисловарь тоже о том же:
> 
> * [сборная солянка](https://ru.wiktionary.org/wiki/%D1%81%D0%B1%D0%BE%D1%80%D0%BD%D0%B0%D1%8F_%D1%81%D0%BE%D0%BB%D1%8F%D0%BD%D0%BA%D0%B0)
> * [солянка](https://ru.wiktionary.org/wiki/%D1%81%D0%BE%D0%BB%D1%8F%D0%BD%D0%BA%D0%B0)

Забавно, у меня за жизнь сложилось как раз противоположное понимание :)

2022-05-29 07:22 UTC, WerySkok commented on ru.json
> +		"combat": "Боевые",
Слишком неформально

2022-05-29 14:26 UTC, Felix14-v2 commented on ru.json
> +		"combat": "Боевые",
Почему? Это вполне формальный термин, которым в принципе играх обозначается всё, что связано с PvP/PvE.

2022-05-29 17:48 UTC, Brawaru commented
Чтобы продолжить перевод, пожалуйста, используйте Crowdin: https://ru.crowdin.com/project/modrinth.

2022-05-29 17:48 UTC, closed without merging