Add german translation
modrinth/translations pull request #6
Opened 2022-05-28 09:13 UTC by mooziii

If have any suggestions or improvement ideas please comment

2022-05-28 19:24 UTC, m44ster commented on de.json
> +			"home": "Go home",
I would change "Go home" to "Zur Startseite" or "Gehe zur Startseite"

2022-05-28 19:44 UTC, Siphalor requested changes
This seems mostly good, I just got some minor spelling fixes and a few expressions that could be translated better imo :+1:

2022-05-28 19:44 UTC, Siphalor commented on de.json
> +		"kitchen-sink": "Kitchen Sink",
Maybe there's a better expression for this in German? Like "Von Allem Etwas" oder "Für alle Etwas"

2022-05-28 19:44 UTC, Siphalor commented on de.json
> +		"quests": "Quests",
Maybe use "Aufgaben" instead of quests?

2022-05-28 19:44 UTC, Siphalor commented on de.json
> +		"lightweight": "Lightweight",
I don't really have a good suggestion for this one, but I think "lightweight" should be translated.

2022-05-28 19:44 UTC, Siphalor commented on de.json
> +			"featured_versions": "Vorgestellte Versionen",
Doesn't sound good.

Some suggestion (not really happy with these either): "Priorisierte Versionen", "Empfohlene Versionen" or "Markierte Versionen".

2022-05-28 20:05 UTC, macbrayne reviewed
I'm not sure how much English German viewers can manage. But if we can assume a certain level of "Minecraft"-specific English proficiency you could get rid of the translations for worldgen and kitchen sink? Does make the site less accessible though to people who don't know these terms (especially kitchen sink is pretty unintuitive, also makes it hard to translate).

EDIT: Sorry, I had accidentally reloaded the page after reviewing and before submitting the review and apparently GitHub did save it without telling me - so in the end I wrote everything twice and some comments might be duplicate.

2022-05-28 22:07 UTC, mooziii commented on de.json
> +		"trash": "Müll",
dont ask me, its in the english translation file so i translated it, idk where its actually used

2022-05-28 22:12 UTC, Eskaan requested changes

2022-05-28 22:12 UTC, venashial commented on de.json
> +		"trash": "Müll",
The `good` and `trash` tags are used on the staging server → https://staging.modrinth.com/

2022-05-28 22:13 UTC, Eskaan commented
Created a pr on https://github.com/mooziii/modrinth-translations/pull/1 fixing the current issues (what I see at least)

2022-05-28 22:18 UTC, Eskaan commented on de.json
> +		"library": "Library",
Yeah, I think it should stay as Library beacuse its not a Library as Bücherei/Bibliothek but as a programming term.

2022-05-28 22:20 UTC, mooziii commented on de.json
> +		"library": "Library",
Changed it to Bibliothek just to make it more german

2022-05-28 22:21 UTC, mooziii commented on de.json
> +				"unsupported": "Inkompatibel",
`incompatible` exists? cant find it in the english translation and whats the difference between those two?

2022-05-28 22:24 UTC, Eskaan commented on de.json
> +				"unsupported": "Inkompatibel",
Support is the english Unterstützung, so unsupported is the no of supported -> Nicht Unterstützt.
Incompatible is just outright translated to Inkompatibel in german, meaning something is not possible to use whit something else

2022-05-28 22:27 UTC, mooziii commented on de.json
> +		"lightweight": "Lightweight",
I know but i also don't know how to translate lightweight into german

2022-05-28 22:28 UTC, m44ster commented on de.json
> +			"project_missing": "Das {type} nach dem du gesucht hast, wurde nicht gefunden.",
I've no idea what shudder should mean but Mod is short for [Modifikation](https://www.duden.de/rechtschreibung/Modifikation) and that can't be neutral
so imo #12 is the only solution to make it correct

2022-05-28 22:28 UTC, mooziii commented on de.json
> +		"cursed": "Cursed",
Verrückt?
idk i wouldn't change this

2022-05-29 07:16 UTC, mooziii commented on de.json
> +			"404": "Oh oh, sieht aus als hättest du dich im [Labyrinth](https://github.com/modrinth/labrinth) verloren.<br />Die Seite nach der du gesucht hast, wurde nicht gefunden.",
got already changed to verlaufen

2022-05-29 07:20 UTC, mooziii commented on de.json
> +		"challenging": "Herausforderungen",
I think Herausfordernd sounds better

2022-05-29 07:25 UTC, mooziii commented on de.json
> +		"all": "Alles"
yea, i changed it

2022-05-29 07:36 UTC, mooziii commented
Everything thats left is a translation for `lightweight` if i see correctly

2022-05-29 08:54 UTC, macbrayne approved these changes
Looking good!

2022-05-29 08:54 UTC, macbrayne commented on de-DE.json
> +		"following": "Abonniert",
Not sure about Abonniert. The Duden definition of Gefolgt seems closer. At the same time YT calls it Abo etc. so 🤷 

In the end it probably doesn't really matter.

[1] https://www.duden.de/rechtschreibung/Abonnement
> für eine längere Zeit vereinbarter und deshalb meist verbilligter Bezug von Zeitungen, Eintrittskarten, digitalen Angeboten o.    Ä.

[2] https://www.duden.de/rechtschreibung/folgen
Section e):
> in einem sozialen Netzwerk Nachrichten eines bestimmten Nutzers regelmäßig empfangen

2022-05-29 08:54 UTC, macbrayne commented on de-DE.json
> +			"404": "Oh oh, sieht aus als hättest du dich im [Labyrinth](https://github.com/modrinth/labrinth) verlaufen.<br />Die gefragte Seite wurde nicht gefunden.",
Still think verirrt fits a lab(y)rinth better :P

2022-05-29 08:58 UTC, Siphalor commented on de.json
> +		"lightweight": "Lightweight",
Hm, what about using "Leichtgewichtig" or "Pflegeleicht"?

While the latter is from a different context, I like it particularly more than the literal translation ^^

2022-05-29 09:10 UTC, Eskaan approved these changes
Find ich gut so

2022-05-29 09:57 UTC, mooziii commented on de-DE.json
> +		"following": "Abonniert",
Gefolgt sounds kinda weird in the context where its used so i think Abonniert would be better

2022-05-29 09:57 UTC, mooziii commented on de-DE.json
> +			"404": "Oh oh, sieht aus als hättest du dich im [Labyrinth](https://github.com/modrinth/labrinth) verlaufen.<br />Die gefragte Seite wurde nicht gefunden.",
changed :)

2022-05-29 10:07 UTC, mooziii commented
New translation keys were added to the english translation so i have to translate them too.
would appreciate it very much if anyone can add them to the german file, if not i will do it as soon as i have time for it

2022-05-29 10:50 UTC, jakobkmar commented
I will translate the new entries.

2022-05-29 12:20 UTC, mooziii commented on de-DE.json
> +			"edit_member": "Mitglieder bearbeiten",
I know that bearbeiten is the correct translation here but i think verwalten would be better?

2022-05-29 12:23 UTC, jakobkmar commented on de-DE.json
> +			"edit_member": "Mitglieder bearbeiten",
yes you are right
```suggestion
			"edit_member": "Mitglieder verwalten",
```

2022-05-29 12:25 UTC, mooziii commented
thank you!

2022-05-29 14:22 UTC, jakobkmar commented on de.json
> +		"lightweight": "Lightweight",
"Pflegeleicht" seems really weird too me, and "Leichtgewicht" was my first thought, but it's not really the same meaning, as in German in sounds like "not many features" while in English it is more obvious that it can also mean "very good performance".

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +				"description": "Gestützt von einer komplett Dokumentierten API, was Launcher und weitere Integrationen von Dritten ermöglicht."
Dokumentierten → dokumentierten, komplett → vollständig (sounds better to me)

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +		"description": "Finde spaßige und qualitativ hochwertige Minecraft Inhalte auf unserer quelloffenen Modplatform - gebaut für die Community. Zauber etwas, werde bezahlt*, und veröffentliche dein Pro
Modplatform → Modplattform

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"minecraft_versions": "Minecraft versionen",
Minecraft versionen→ Minecraft Versionen

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"confirm": "Bist du sicher, dass du diesen Bild aus der Galerie entfernen möchtest?",
diesen → dieses

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"action": "Besitztum übertragen"
Besitztum → Besitz

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"body": "Wenn du deinen Account einmal gelöscht hast, gibt es kein Zurück mehr. Deinen Account zu löschen heißt, dass auch alle Daten die zu ihm gehören von unseren Servern gelöscht werden, einsch
dass auch alle Daten die zu ihm gehören von unseren Servern gelöscht werden → dass auch alle Daten, die zu ihm gehören, von unseren Servern gelöscht werden

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"confirm_body": "Dies wird **sofort alle deine Projekte löschen**, einschließlich deren Abonnenten. Den Account zu löschen kann nicht rückgängig gemacht werden.\n\nWenn du hilfe mit deinem Account
support → Support
Maybe instead of "Den Account zu löschen kann nicht rückgängig gemacht werden" → "Eine Accountlöschung kann nicht rückgängig gemacht werden"?

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"body": "Das Modrinth Token zu invalidieren kann unerwartete Folgen haben. Bitte sei dir bewusst, dass das folgende kaputt gehen könnte:\n - jede Anwendung die dein Token nutzt um mit der API zu i
_Das → Den_
das folgende → folgendes
_falsches → falschen_
GitHub action → GitHub Action
_neues Token → neuer Token_

Apparently token can also be neutral, never heard of that but according to [Duden](https://www.duden.de/rechtschreibung/Token) it's apparently correct? So the cursive things might be ok...

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +		"how_to": "Drag and drop zum hochladen oder zum Auswählen klicken"
drop → Drop
hochladen → Hochladen

2022-05-29 14:37 UTC, macbrayne commented on de-DE.json
> +			"line2": "Dein Adblocker hielt Modrinth davon ab Werbung anzuzeigen - unsere einzige Einnahmequelle.",
hielt → hält

2022-05-29 14:37 UTC, macbrayne commented on en.json
> +				"en-GB": "English (UK)",
doesn't exist anymore

2022-05-29 14:39 UTC, Siphalor commented on de-DE.json
> +			"minecraft_versions": "Minecraft versionen",
or even "Minecraft-Versionen"

2022-05-29 14:40 UTC, Siphalor commented on de-DE.json
> +			"action": "Besitztum übertragen"
Und natürlich entsprechend angepasst: "Übertrage den Besitz dieses Projekts auf einen anderen Nutzer."

2022-05-29 14:42 UTC, Siphalor commented on de-DE.json
> +			"description": "Ein Projekt zu löschen führt zum verlust aller Daten, einschließlich der Versionen.",
verlust ➡ Verlust

2022-05-29 14:43 UTC, Siphalor commented on de-DE.json
> +		"release_channel": "Release Kanal",
Besser zusammen als "Release-Kanal" soweit Release bereits als Begriff feststeht)

2022-05-29 14:46 UTC, Siphalor commented on de-DE.json
> +			"placeholder": "E-Mail hinzufügen ..."
I am not sure where this is displayed, but "hinzufügen" is probably not the right choice.
Probably "ändern", "setzen" or "eingeben" is more appropriate.

2022-05-29 14:47 UTC, Siphalor commented on de-DE.json
> +			"confirm_body": "Dies wird **sofort alle deine Projekte löschen**, einschließlich deren Abonnenten. Den Account zu löschen kann nicht rückgängig gemacht werden.\n\nWenn du hilfe mit deinem Account
Or just use "Unterstützung" or "Hilfe" instead of "Support".

2022-05-29 14:54 UTC, jakobkmar commented on de-DE.json
> +			"body": "Das Modrinth Token zu invalidieren kann unerwartete Folgen haben. Bitte sei dir bewusst, dass das folgende kaputt gehen könnte:\n - jede Anwendung die dein Token nutzt um mit der API zu i
mh token was definetly neutral for me before, but now that you say it, it seems like this comes down to personal preference

2022-05-29 15:01 UTC, Siphalor commented on de-DE.json
> +			"body": "Das Modrinth Token zu invalidieren kann unerwartete Folgen haben. Bitte sei dir bewusst, dass folgendes kaputt gehen könnte:\n - jede Anwendung die dein Token nutzt um mit der API zu inte
I think in this context "folgendes" is a noun and should be capitalized.

2022-05-29 15:02 UTC, Siphalor commented on de-DE.json
> +		"how_to": "Drag and Drop zum Hochladen oder zum Auswählen klicken"
[The Duden recommends](https://www.duden.de/rechtschreibung/Drag_and_drop) "Drag-and-drop" :)

2022-05-29 15:12 UTC, mooziii commented on de-DE.json
> +		"release_channel": "Release Kanal",
sag mal warum schreibst du manchmal deutsch manchmal englisch

2022-05-29 15:15 UTC, Siphalor commented on de-DE.json
> +		"release_channel": "Release Kanal",
Well, I want to write in English. But when proofreading German I sometimes fall back to German and only really notice it when I begin to write the next comment in English ^^

I think I edited all of my comments accordingly. Of course, this is not reflected in the email notifications.
That damage is already done :/

2022-05-29 17:48 UTC, venashial commented
Closing this as the German translation on Crowdin is complete.

2022-05-29 17:48 UTC, closed without merging